export type Epigram = {
  likeCount: number;
  tags: { name: string; id: number; }[];
  writerId: number;
  referenceUrl: string;
  referenceTitle: string;
  author: string;
  content: string;
  id: number;
};

export const mockData: { totalCount: number; nextCursor: number; list: Epigram[] } = {
  totalCount: 20,
  nextCursor: 0,
  list: [
    {
      likeCount: 34,
      tags: [{ name: "우울할 때", id: 1 },{ name: "동기부여", id: 2 },{ name: "나아가야 할 때", id: 3 }],
      writerId: 1,
      referenceUrl: "http://example.com/1",
      referenceTitle: "참조 제목 1",
      author: "앙드레 말로",
      content: "오랫동안 꿈을 그리는 사람은 마침내 그 꿈을 닮아 간다.",
      id: 1,
    },
    {
      likeCount: 56,
      tags: [{ name: "성공한 삶", id: 1 }],
      writerId: 2,
      referenceUrl: "http://example.com/2",
      referenceTitle: "참조 제목 2",
      author: "윈스턴 처칠",
      content: "성공은 최종적이지 않으며, 실패는 치명적이지 않다. 중요한 것은 계속하는 용기다.",
      id: 2,
    },
    {
      likeCount: 78,
      tags: [{ name: "지혜", id: 1 }],
      writerId: 3,
      referenceUrl: "http://example.com/3",
      referenceTitle: "참조 제목 3",
      author: "소크라테스",
      content: "너 자신을 알라.",
      id: 3,
    },
    {
      likeCount: 90,
      tags: [{ name: "철학", id: 1 }],
      writerId: 4,
      referenceUrl: "http://example.com/4",
      referenceTitle: "참조 제목 4",
      author: "니체",
      content: "살아있는 모든 것은 고통을 겪는다.",
      id: 4,
    },
    {
      likeCount: 12,
      tags: [{ name: "사랑", id: 1 }],
      writerId: 5,
      referenceUrl: "http://example.com/5",
      referenceTitle: "참조 제목 5",
      author: "괴테",
      content: "사랑하는 것은 아무것도 아닌 것이고, 사랑받는 것은 무언가인 것이며, 사랑하는 것과 사랑받는 것은 모든 것이다.",
      id: 5,
    },
    {
      likeCount: 23,
      tags: [{ name: "인내", id: 1 }],
      writerId: 6,
      referenceUrl: "http://example.com/6",
      referenceTitle: "참조 제목 6",
      author: "톨스토이",
      content: "인내는 쓰지만 열매는 달다.",
      id: 6,
    },
    {
      likeCount: 45,
      tags: [{ name: "행복", id: 1 }],
      writerId: 7,
      referenceUrl: "http://example.com/7",
      referenceTitle: "참조 제목 7",
      author: "아리스토텔레스",
      content: "행복은 우리가 하는 일에서 오는 것이다.",
      id: 7,
    },
    {
      likeCount: 67,
      tags: [{ name: "삶", id: 1 }],
      writerId: 8,
      referenceUrl: "http://example.com/8",
      referenceTitle: "참조 제목 8",
      author: "마크 트웨인",
      content: "20년 후, 당신은 했던 일보다 하지 않았던 일로 인해 더 실망할 것이다.",
      id: 8,
    },
    {
      likeCount: 89,
      tags: [{ name: "성공", id: 1 }],
      writerId: 9,
      referenceUrl: "http://example.com/9",
      referenceTitle: "참조 제목 9",
      author: "알버트 아인슈타인",
      content: "성공한 사람이 되려고 노력하지 말고, 가치 있는 사람이 되려고 노력하라.",
      id: 9,
    },
    {
      likeCount: 10,
      tags: [{ name: "지혜", id: 1 }],
      writerId: 10,
      referenceUrl: "http://example.com/10",
      referenceTitle: "참조 제목 10",
      author: "공자",
      content: "지혜로운 사람은 물을 좋아하고, 인자한 사람은 산을 좋아한다.",
      id: 10,
    },
    {
      likeCount: 22,
      tags: [{ name: "철학", id: 1 }],
      writerId: 11,
      referenceUrl: "http://example.com/11",
      referenceTitle: "참조 제목 11",
      author: "데카르트",
      content: "나는 생각한다, 고로 존재한다.",
      id: 11,
    },
    {
      likeCount: 33,
      tags: [{ name: "사랑", id: 1 }],
      writerId: 12,
      referenceUrl: "http://example.com/12",
      referenceTitle: "참조 제목 12",
      author: "셰익스피어",
      content: "사랑은 눈으로 보지 않고 마음으로 본다.",
      id: 12,
    },
    {
      likeCount: 44,
      tags: [{ name: "인내", id: 1 }],
      writerId: 13,
      referenceUrl: "http://example.com/13",
      referenceTitle: "참조 제목 13",
      author: "벤자민 프랭클린",
      content: "인내는 쓰지만 그 열매는 달다.",
      id: 13,
    },
    {
      likeCount: 55,
      tags: [{ name: "행복", id: 1 }],
      writerId: 14,
      referenceUrl: "http://example.com/14",
      referenceTitle: "참조 제목 14",
      author: "헬렌 켈러",
      content: "행복의 문이 하나 닫히면 다른 문이 열린다.",
      id: 14,
    },
    {
      likeCount: 57,
      tags: [{ name: "새로운 영감", id: 1 }],
      writerId: 15,
      referenceUrl: "http://example.com/14",
      referenceTitle: "참조 제목 15",
      author: "파우울로 코엘료",
      content: "이 세상에는 위대한 진실이 하나 있어. 무언가를 온 마음을 다해 원한다면, 반드시 그렇게 된다는 거야.",
      id: 15,
    },
  ]
};